name: remove_markdown
description: Strip markdown from markdown formatted string.
version: 0.0.1
homepage: https://github.com/wizlif/remove_markdown

environment:
  sdk: '>=2.19.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
