# ==================================================
# This is the main worflow for testing and analyzing
# the code.
# ==================================================

name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches: 
      - master
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Fetch code from repository
        uses: actions/checkout@v3
      - run: rm -rf example
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.1
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: dart test --coverage=./coverage
      - name: Get code coverage files
        id: get_codecov_files
        run: |
          echo "CODECOV_FILES=$(
            find . -name 'lcov.info' -print0 | tr '\0' , | sed 's/,$//'
          )" >> $GITHUB_OUTPUT
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
          fail_ci_if_error: true
          file: ${{ steps.get_codecov_files.outputs.CODECOV_FILES }}
